name: Lua CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  lint:
    name: Lint & Format Lua Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: 5.1

      - name: Setup Lua + Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Cache luarocks packages
        uses: actions/cache@v4
        with:
          path: ~/.luarocks
          key: luarocks-${{ runner.os }}-v1

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Format Lua code with Stylua
        uses: JohnnyMorganz/stylua-action@v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: '**/*.lua'

      - name: Cache WoW API stubs
        uses: actions/cache@v4
        with:
          path: WoWStubs
          key: wowstubs-${{ hashFiles('.github/workflows/lua.yml') }}

      - name: Clone WoW API stubs (if not cached)
        if: steps.cache-wow-api-stubs.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/Ketho/vscode-wow-api.git WoWStubs

      - name: Cache Lua Language Server
        id: lsp-cache
        uses: actions/cache@v4
        with:
          path: |
            lua-language-server
            lua-language-server/bin
            lua-language-server/3rd/luamake
          key: lua-language-server-cache-v1

      - name: Clone Lua Language Server (if not cached)
        if: steps.lsp-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/LuaLS/lua-language-server.git
          cd lua-language-server
          git submodule update --init --recursive

      - name: Build Lua Language Server (if not cached)
        if: steps.lsp-cache.outputs.cache-hit != 'true'
        run: |
          cd lua-language-server/3rd/luamake
          ./compile/install.sh
          cd ../..
          ./3rd/luamake/luamake rebuild

      - name: Run Lua Language Server check
        run: |
          find . -type f -name '*.lua' \
            ! -path './WoWStubs/*' \
            ! -path './.github/*' \
            -print0 | xargs -0 ./lua-language-server/bin/lua-language-server --check

      - name: Run luacheck (main code)
        run: |
          luacheck Core.lua API/ Modules/ Media/ --config .luacheckrc || echo "::warning::Luacheck reported issues"

      - name: Run luacheck (Locales - no line length check)
        run: |
          luacheck Locales/ --config .luacheckrc --no-max-line-length || echo "::warning::Luacheck reported issues"

      - name: Check TOC Interface version
        run: |
          grep -E "^## Interface: " *.toc || echo "::warning::No Interface version found in .toc file"

      - name: Check for changes after formatting
        id: git-diff
        run: |
          if git diff --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push formatted code
        if: steps.git-diff.outputs.no_changes == 'false'
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "style: auto-format code with stylua"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
