name: Lua CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  lint:
    name: Lint & Format Lua Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build unzip curl luarocks

      - name: Install luacheck
        run: sudo luarocks install luacheck

      - name: Format Lua code with Stylua
        uses: JohnnyMorganz/stylua-action@v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
          args: Core.lua API/ Modules/ Locales/ Media/

      - name: Clone WoW API stubs
        run: |
          git clone --depth=1 https://github.com/Ketho/vscode-wow-api.git WoWStubs

      - name: Cache Lua Language Server
        uses: actions/cache@v4
        with:
          path: lua-language-server
          key: lua-language-server-v3

      - name: Set up Lua Language Server
        run: |
          if [ ! -d "lua-language-server" ]; then
            git clone https://github.com/LuaLS/lua-language-server.git
            cd lua-language-server
            git submodule update --init --recursive
            cd 3rd/luamake
            ./compile/install.sh
            cd ../..
            ./3rd/luamake/luamake rebuild
          fi

      - name: Run Lua Language Server check
        run: |
          ./lua-language-server/bin/lua-language-server --check \
            Core.lua \
            Modules/Clicker.lua \
            Modules/Shadow.lua \
            API/FrameState.lua \
            Media/Textures/TextureList.lua \
            Locales/deDE.lua \
            Locales/enUS.lua \
            Locales/esES.lua \
            Locales/frFR.lua \
            Locales/itIT.lua \
            Locales/koKR.lua \
            Locales/ptBR.lua \
            Locales/ruRU.lua \
            Locales/zhCN.lua \
            Locales/zhTW.lua

      - name: Run luacheck (main code)
        run: |
          luacheck Core.lua API/ Modules/ Media/ --config .luacheckrc || true

      - name: Run luacheck (Locales - no line length check)
        run: |
          luacheck Locales/ --config .luacheckrc --no-max-line-length || true

      - name: Set up git remote for pushing
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and push formatted code
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "style: auto-format code with stylua"
          add: "."
          pull: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
