name: Lua CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  lint:
    name: Lint & Format Lua Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build unzip curl luarocks

      - name: Install luacheck
        run: sudo luarocks install luacheck

      - name: Format Lua code with Stylua
        uses: JohnnyMorganz/stylua-action@v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
          args: Core.lua API/ Modules/ Locales/ Media/

      - name: Clone WoW API stubs
        run: |
          git clone --depth=1 https://github.com/Ketho/vscode-wow-api.git WoWStubs

      - name: Cache Lua Language Server
        id: lsp-cache
        uses: actions/cache@v4
        with:
          path: |
            lua-language-server
            lua-language-server/bin
            lua-language-server/3rd/luamake
          key: lua-language-server-cache-v1

      - name: Clone Lua Language Server (if not cached)
        if: steps.lsp-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/LuaLS/lua-language-server.git
          cd lua-language-server
          git submodule update --init --recursive

      - name: Build Lua Language Server (if not cached)
        if: steps.lsp-cache.outputs.cache-hit != 'true'
        run: |
          cd lua-language-server/3rd/luamake
          ./compile/install.sh
          cd ../..
          ./3rd/luamake/luamake rebuild


      - name: Run Lua Language Server check
        run: |
          ./lua-language-server/bin/lua-language-server --check \
            Core.lua \
            Modules/Clicker.lua \
            Modules/Shadow.lua \
            API/FrameState.lua \
            Media/Textures/TextureList.lua \
            Locales/deDE.lua \
            Locales/enUS.lua \
            Locales/esES.lua \
            Locales/frFR.lua \
            Locales/itIT.lua \
            Locales/koKR.lua \
            Locales/ptBR.lua \
            Locales/ruRU.lua \
            Locales/zhCN.lua \
            Locales/zhTW.lua

      - name: Run luacheck (main code)
        run: |
          luacheck Core.lua API/ Modules/ Media/ --config .luacheckrc || true

      - name: Run luacheck (Locales - no line length check)
        run: |
          luacheck Locales/ --config .luacheckrc --no-max-line-length || true

      - name: Check TOC Interface version
        run: |
          grep -E "^## Interface: " *.toc || echo "::warning::No Interface version found in .toc file"

      #- name: Set up git remote for pushing
      #  run: |
      #    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Check for changes after formatting
        id: git-diff
        run: |
          if git diff --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push formatted code
        if: steps.git-diff.outputs.no_changes == 'false'
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "style: auto-format code with stylua"
          add: "."
          pull: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
